# Generated by Django 4.2.30 on 2026-08-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
    ]
